export const mockJobPostings = [
  {
    id: 'software-engineer-frontend',
    title: 'Software Engineer, Frontend',
    status: 'open',
    team: 'Engineering',
    location: 'Mountain View, CA',
    compensation: '120,000 - 150,000',
    description: '<p>We are looking for a talented Frontend Engineer to join our team and help build the future of our user interface.</p>',
    createdAt: new Date('2023-10-26T10:00:00Z'),
  },
  {
    id: 'product-manager-mobile',
    title: 'Product Manager, Mobile',
    status: 'open',
    team: 'Product',
    location: 'New York, NY',
    compensation: '140,000 - 170,000',
    description: '<p>As a Product Manager for our mobile applications, you will define the roadmap and work with a cross-functional team to deliver a world-class experience.</p>',
    createdAt: new Date('2023-10-25T14:30:00Z'),
  },
  {
    id: 'ux-designer',
    title: 'UX Designer',
    status: 'open',
    team: 'Design',
    location: 'Remote',
    compensation: '110,000 - 135,000',
    description: '<p>We are seeking a creative UX Designer to design intuitive and engaging user experiences across our web and mobile platforms.</p>',
    createdAt: new Date('2023-10-24T11:00:00Z'),
  },
];
